* py_rsync: A pythonic high-level wrapper for ~rsync~

While ~rsync~ seems like a very simple tool it has a large number of
advanced and complex features. So much so that I find using and
writing command line invocations (beyond very simple ones) to be quite
complicated and I start to want to actually script the generation of
them. This is the niche this library will hopefully provide.

While there are some other C-level libraries and alternative
implementations of the core delta-compression rsync algorithm out
there none are as fully featured as the standard unix command line
application. Ideally a pure python or wrapped C/C++ library that
includes all this functionality would be preferrable but even becoming
fluent in the entire interface is a challenge, that hopefully this
library makes easier for future improvements in data-syncing libraries.



** Docs and Info

See the [[file:./info][info]] directory for the documentation and history of the
project. The [[file:./info/README.org][README]] serves as an index. These files are (mostly) in
emacs org-mode and serve as the primary source of documentation. 

Other "rendered" versions may exist and be published. The default
location is at
[[https://salotz.github.io/py_rsync][salotz.github.io/py_rsync]]
in HTML rendered with Sphinx.

** COMMENT Maintenance Intent

** Developing

See the [[file:info/dev_guide.org][Developers Guide]] for developing.
